name = "SayHello"
uuid = "a9064840-57cf-463b-9e62-ed1e2d272500"
authors = ["dhtan <dinghangtan@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
